import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AlbumCard } from "@/components/album-card";
import { RatingDisplay } from "@/components/rating-display";
import { albums, getAlbum } from "@/data/albums";
export function generateStaticParams() { return albums.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const album = getAlbum((await params).slug); return { title: album ? `${album.title} — ${album.artist} | DOL ZIKLUB` : "Album introuvable" }; }
export default async function AlbumPage({ params }: { params: Promise<{ slug: string }> }) { const album = getAlbum((await params).slug); if (!album) notFound(); const related = albums.filter((item) => item.id !== album.id).slice(0, 3); return <main className="page album-page"><Link className="back" href="/albums">← Retour au bac</Link><section className="album-sheet"><div className="album-sheet__cover">{album.cover && <Image src={album.cover} alt={`Pochette de ${album.title}`} fill sizes="(max-width: 700px) 90vw, 40vw" priority />}</div><div><p className="eyebrow">FICHE D’ARCHIVE</p><h1>{album.title}<br/><em>{album.artist}</em></h1><RatingDisplay rating={album.rating} /><dl><div><dt>Proposé par</dt><dd>À documenter</dd></div><div><dt>Écouté par</dt><dd>À documenter</dd></div><div><dt>Statut</dt><dd>En attente de données</dd></div></dl><p className="notice">La pochette a été retrouvée, mais les notes, avis, liens et métadonnées de la feuille historique n’ont pas été fournis. Cette fiche ne les invente pas.</p></div></section><section className="review-sheet"><div><p className="eyebrow">VERDICT</p><h2>Le compte rendu est encore sous scellés.</h2><p>Dès que les données source seront disponibles, l’avis sera attribué à la personne ayant réellement écouté l’album.</p></div><div className="track-box"><b>Best track</b><span>À documenter</span><b>Worst track</b><span>À documenter</span></div></section><section className="section"><div className="section-heading"><h2>À fouiller ensuite</h2></div><div className="album-grid">{related.map((item) => <AlbumCard key={item.id} album={item} />)}</div></section></main>; }
