"use client";

import Link from "next/link";
import Image from "next/image";
import { type FormEvent, useCallback, useEffect, useState } from "react";
import { members } from "@/data/members";
import { getSupabaseBrowserClient, isSupabaseConfigured } from "@/lib/supabase/client";
import { RatingDisplay } from "@/components/rating-display";
import type { Album } from "@/types/album";

type Tab = "archive" | "selection" | "kouize" | "admin";
type SignedMember = { id: string; username: string; displayName: string };
type DrawEntry = { id: string; draw_number: number; position: number; proposed_by: string | null; listened_by: string | null; proposed_by_name: string | null; listened_by_name: string | null; album_title: string | null; album_artist: string | null; cover_path: string | null };
type ReviewRecord = { album_id: string; review: string; rating: number; best_track: string | null; worst_track: string | null };
type ReviewPayload = { entryId: string; review: string; rating: number; bestTrack: string; worstTrack: string };
type ProposalPayload = { entryId: string; title: string; artist: string; file: File | null };
type KouizeAnswer = { member_username: string; question_key: string; answer: string };

const tabs: Array<{ id: Exclude<Tab, "admin">; label: string; hint: string }> = [
  { id: "archive", label: "Tirages", hint: "Les archives et les tirages actifs du club" },
  { id: "selection", label: "Sélection", hint: "Tes propositions et tes écoutes à rendre" },
  { id: "kouize", label: "Kouize", hint: "Les goûts et curiosités des membres" },
];
const adminTab = { id: "admin" as const, label: "Préparer les tirages", hint: "Administration des prochains tirages" };
const roster = members.flatMap((member) => member.username ? [{ username: member.username, displayName: member.displayName }] : []);
const ratingChoices = Array.from({ length: 11 }, (_, index) => index / 2);
const quizMembers = ["Toma", "Pep", "Motem", "Bono", "Dod", "Yuna", "Chacha", "Enzo", "Kougna", "Alain"];
const quizQuestions = [
  { key: "default_style", label: "DÉPART", question: "Ton univers sonore par défaut", prompt: "Le style qui revient naturellement dans tes écoutes." },
  { key: "dislikes", label: "NOPE", question: "Le son que tu zappes sans hésiter", prompt: "Ce qui a très peu de chances de te convaincre." },
  { key: "curiosity", label: "DÉTOUR", question: "Le territoire musical qui t’intrigue", prompt: "Le genre ou l’univers que tu veux mieux explorer." },
  { key: "first_hook", label: "DÉCLIC", question: "Ce qui te capte dès les premières secondes", prompt: "L’élément qui te fait tendre l’oreille en premier." },
];

function memberName(name: string | null) { return name ? `${name.slice(0, 1).toLocaleUpperCase()}${name.slice(1)}` : "—"; }
function value(input: string | null) { return input?.trim() || "—"; }
function coverUrl(path: string | null) { return path ? getSupabaseBrowserClient().storage.from("album-covers").getPublicUrl(path).data.publicUrl : null; }

function MemberSelect({ value, onChange, label }: { value: string | null; onChange: (next: string) => void; label: string }) {
  return <select value={value ?? ""} onChange={(event) => onChange(event.target.value)} aria-label={label}><option value="">—</option>{roster.map((member) => <option key={member.username} value={member.username}>{member.displayName}</option>)}</select>;
}

function TrackLink({ album, kind }: { album: Album; kind: "bestTrack" | "worstTrack" }) {
  const track = album[kind];
  if (!track.title) return <span className="sheet-track-empty">—</span>;
  const url = track.url ?? `https://music.youtube.com/search?q=${encodeURIComponent(`${album.artist} ${track.title}`)}`;
  return <a className={`sheet-track-link sheet-track-link--${kind === "bestTrack" ? "best" : "worst"}`} href={url} target="_blank" rel="noreferrer">{track.title}<span>↗</span></a>;
}

function HistoricalDraws({ albums }: { albums: Album[] }) {
  const ordered = [...albums].sort((a, b) => Number(a.id.replace("archive-", "")) - Number(b.id.replace("archive-", "")));
  const placeholder = (id: string, proposedBy: string, listenedBy: string): Album => ({ id, slug: id, title: "Album – Artiste", artist: "", cover: null, releaseYear: null, origin: null, language: null, genres: [], projectType: null, proposedBy, listenedBy, rating: null, shortReview: "Avis à compléter", detailedReview: null, bestTrack: { title: null, url: null }, worstTrack: { title: null, url: null }, albumUrl: null, artistDescription: null, albumDescription: null, status: "pending" });
  const inRange = (from: number, to: number) => ordered.filter((album) => { const position = Number(album.id.replace("archive-", "")); return position >= from && position <= to; });
  const groups = [inRange(1, 10), inRange(11, 19), inRange(20, 28), inRange(29, 37), inRange(38, 45), [placeholder("pending-yuna-enzo", "Yuna", "Enzo"), ...inRange(46, 46), placeholder("pending-enzo-motem", "Enzo", "Motem"), ...inRange(47, 49), placeholder("pending-chacha-bono", "Chacha", "Bono"), placeholder("pending-bono-chacha", "Bono", "Chacha")]];
  return <>{groups.map((group, index) => <section className="draw-section" key={index}><div className="draw-heading"><span className="eyebrow">TIRAGE {String(index + 1).padStart(2, "0")}</span><span>{group.length} albums classés</span></div><div className="sheet-scroll"><table className="sheet-table"><thead><tr><th>Album · Artiste</th><th>Proposé par</th><th>Écouté par</th><th>Avis</th><th>Note</th><th>Best Track</th><th>Worst Track</th></tr></thead><tbody>{group.map((album) => <tr key={album.id}><td><Link className="sheet-album-link" href={`/albums/${album.slug}`}><b>{album.title}</b><span>{album.artist}</span></Link></td><td><span className="sheet-member">{memberName(album.proposedBy)}</span></td><td><span className="sheet-member">{memberName(album.listenedBy)}</span></td><td className="sheet-review">{value(album.shortReview)}</td><td><RatingDisplay rating={album.rating} /></td><td><TrackLink album={album} kind="bestTrack" /></td><td><TrackLink album={album} kind="worstTrack" /></td></tr>)}</tbody></table></div></section>)}</>;
}

function LiveDraws({ entries, member, onOpenProposal, onOpenReview }: { entries: DrawEntry[]; member: SignedMember | null; onOpenProposal: (id: string) => void; onOpenReview: (id: string) => void }) {
  const draws = new Map<number, DrawEntry[]>();
  entries.forEach((entry) => draws.set(entry.draw_number, [...(draws.get(entry.draw_number) ?? []), entry]));
  return <>{[...draws.entries()].map(([drawNumber, rows]) => <section className="draw-section draw-section--live" key={drawNumber}><div className="draw-heading"><span className="eyebrow">TIRAGE {String(drawNumber).padStart(2, "0")}</span><span>{rows.length} emplacement{rows.length > 1 ? "s" : ""} en cours</span></div><div className="sheet-scroll"><table className="sheet-table"><thead><tr><th>Album · Artiste</th><th>Proposé par</th><th>Écouté par</th><th>État</th></tr></thead><tbody>{rows.sort((a, b) => a.position - b.position).map((entry) => { const canPropose = member?.id === entry.proposed_by; const canReview = member?.id === entry.listened_by && entry.album_title && entry.album_artist; return <tr className={(canPropose || canReview) ? "sheet-row--action" : ""} key={entry.id} onClick={() => canPropose && !entry.album_title ? onOpenProposal(entry.id) : canReview ? onOpenReview(entry.id) : undefined}><td>{entry.album_title ? <span className="sheet-album-link"><b>{entry.album_title}</b><span>{entry.album_artist}</span></span> : <span className="sheet-placeholder-album">Album – Artiste</span>}</td><td><span className="sheet-member">{memberName(entry.proposed_by_name)}</span></td><td><span className="sheet-member">{memberName(entry.listened_by_name)}</span></td><td>{canPropose && !entry.album_title ? <button className="sheet-entry-action" onClick={(event) => { event.stopPropagation(); onOpenProposal(entry.id); }}>Proposer l’album</button> : canReview ? <button className="sheet-entry-action" onClick={(event) => { event.stopPropagation(); onOpenReview(entry.id); }}>Rendre l’écoute</button> : entry.album_title ? <span className="sheet-pending">À écouter</span> : <span className="sheet-pending">En attente</span>}</td></tr>; })}</tbody></table></div></section>)}</>;
}

function ProposalCard({ entry, saving, onSave }: { entry: DrawEntry; saving: boolean; onSave: (payload: ProposalPayload) => void }) {
  const [title, setTitle] = useState(entry.album_title ?? "");
  const [artist, setArtist] = useState(entry.album_artist ?? "");
  const [file, setFile] = useState<File | null>(null);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); onSave({ entryId: entry.id, title, artist, file }); };
  return <article className="review-card proposal-card"><div className="review-card__album">{coverUrl(entry.cover_path) ? <Image unoptimized src={coverUrl(entry.cover_path)!} alt="Pochette proposée" width={90} height={90} /> : <span className="proposal-card__placeholder">POC HETTE</span>}<span className="eyebrow">À PROPOSER</span><h3>Tes choix, ton disque.</h3><p>Renseigne l’album, l’artiste et, si tu veux, sa pochette.</p></div><form className="review-form" onSubmit={submit}><label><span>Titre de l’album</span><input required maxLength={180} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Titre de l’album" /></label><label><span>Artiste</span><input required maxLength={180} value={artist} onChange={(event) => setArtist(event.target.value)} placeholder="Nom de l’artiste" /></label><label className="proposal-cover-field"><span>Pochette (facultative)</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><button type="submit" className="button" disabled={saving}>{saving ? "Enregistrement…" : "Enregistrer mon album"}</button></form></article>;
}

function ReviewCard({ entry, existing, saving, onSave }: { entry: DrawEntry; existing?: ReviewRecord; saving: boolean; onSave: (payload: ReviewPayload) => void }) {
  const [review, setReview] = useState(existing?.review ?? ""); const [rating, setRating] = useState(String(existing?.rating ?? "")); const [bestTrack, setBestTrack] = useState(existing?.best_track ?? ""); const [worstTrack, setWorstTrack] = useState(existing?.worst_track ?? "");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); onSave({ entryId: entry.id, review, rating: Number(rating), bestTrack, worstTrack }); };
  return <article className="review-card"><div className="review-card__album">{coverUrl(entry.cover_path) && <Image unoptimized src={coverUrl(entry.cover_path)!} alt="Pochette de l’album" width={90} height={90} />}<span className="eyebrow">{existing ? "VERDICT ENREGISTRÉ" : "À RENDRE"}</span><h3>{entry.album_title}</h3><p>{entry.album_artist}</p></div><form className="review-form" onSubmit={submit}><label><span>Ton avis</span><textarea required maxLength={2000} value={review} onChange={(event) => setReview(event.target.value)} placeholder="Ton verdict, sans filtre." /></label><label><span>Ta note</span><select required value={rating} onChange={(event) => setRating(event.target.value)}><option value="" disabled>Choisir une note</option>{ratingChoices.map((choice) => <option key={choice} value={choice}>{choice.toFixed(1)} / 5</option>)}</select></label><div className="review-form__tracks"><label><span>Best track</span><input maxLength={160} value={bestTrack} onChange={(event) => setBestTrack(event.target.value)} placeholder="Ton meilleur morceau" /></label><label><span>Worst track</span><input maxLength={160} value={worstTrack} onChange={(event) => setWorstTrack(event.target.value)} placeholder="Le morceau le moins convaincant" /></label></div><button type="submit" className="button" disabled={saving}>{saving ? "Enregistrement…" : existing ? "Mettre à jour mon verdict" : "Enregistrer mon verdict"}</button></form></article>;
}

function SelectionWorkspace({ entries, member, reviews, focusedProposal, focusedReview, savingId, onProposal, onReview }: { entries: DrawEntry[]; member: SignedMember | null; reviews: ReviewRecord[]; focusedProposal: string | null; focusedReview: string | null; savingId: string | null; onProposal: (payload: ProposalPayload) => void; onReview: (payload: ReviewPayload) => void }) {
  const proposals = member ? entries.filter((entry) => entry.proposed_by === member.id) : [];
  const listens = member ? entries.filter((entry) => entry.listened_by === member.id && entry.album_title && entry.album_artist) : [];
  const reviewMap = new Map(reviews.map((review) => [review.album_id, review]));
  const visibleProposals = focusedProposal ? proposals.filter((entry) => entry.id === focusedProposal) : proposals;
  const visibleListens = focusedReview ? listens.filter((entry) => entry.id === focusedReview) : listens;
  return <>{!member ? <section className="review-workspace"><div className="review-workspace__empty"><p>Connecte-toi pour proposer ton album ou rendre une écoute.</p><Link className="button" href="/connexion">Connexion</Link></div></section> : <><section className="review-workspace proposal-workspace"><div className="review-workspace__heading"><div><p className="eyebrow">MES PROPOSITIONS</p><h2>Les albums que je <em>propose.</em></h2><p>Seules les lignes où tu es désigné·e « proposé par » sont accessibles ici.</p></div><span className="review-counter">{proposals.length} slot{proposals.length > 1 ? "s" : ""}</span></div><div className="review-queue">{visibleProposals.length ? visibleProposals.map((entry) => <ProposalCard key={entry.id} entry={entry} saving={savingId === entry.id} onSave={onProposal} />) : <div className="review-workspace__empty"><p>Aucun album à proposer dans les tirages actifs.</p></div>}</div></section><section className="review-workspace"><div className="review-workspace__heading"><div><p className="eyebrow">MES ÉCOUTES À RENDRE</p><h2>Les albums que je dois <em>écouter.</em></h2><p>Seules les lignes où tu es désigné·e « écouté par » peuvent recevoir ton verdict.</p></div><span className="review-counter">{listens.length} écoute{listens.length > 1 ? "s" : ""}</span></div><div className="review-queue">{visibleListens.length ? visibleListens.map((entry) => <ReviewCard key={entry.id} entry={entry} existing={reviewMap.get(entry.id)} saving={savingId === entry.id} onSave={onReview} />) : <div className="review-workspace__empty"><p>Rien à rendre pour l’instant : les albums apparaîtront dès qu’ils seront proposés.</p></div>}</div></section></>}</>;
}

function AdminDraws({ entries, savingId, message, onCreate, onDelete, onAssign }: { entries: DrawEntry[]; savingId: string | null; message: string; onCreate: () => void; onDelete: (draw: number) => void; onAssign: (entry: DrawEntry, proposer: string, listener: string) => void }) {
  const [drafts, setDrafts] = useState<Record<string, { proposer: string; listener: string }>>({});
  const draws = new Map<number, DrawEntry[]>(); entries.forEach((entry) => draws.set(entry.draw_number, [...(draws.get(entry.draw_number) ?? []), entry]));
  const field = (entry: DrawEntry) => drafts[entry.id] ?? { proposer: entry.proposed_by_name ?? "", listener: entry.listened_by_name ?? "" };
  const change = (entry: DrawEntry, key: "proposer" | "listener", next: string) => setDrafts((current) => ({ ...current, [entry.id]: { ...field(entry), [key]: next } }));
  return <section className="draw-sheet admin-draw-sheet"><div className="draw-creator"><div><span className="eyebrow">ADMINISTRATION</span><h3>Préparer un nouveau tirage</h3><p>Crée une feuille vide de huit lignes, puis attribue librement les pseudos « proposé par » et « écouté par ».</p></div><button type="button" className="button" disabled={savingId === "new-draw"} onClick={onCreate}>{savingId === "new-draw" ? "Création…" : "Créer un tirage vide"}</button></div>{message && <p className="selection-message" role="status">{message}</p>}{[...draws.entries()].map(([draw, rows]) => <section className="draw-section" key={draw}><div className="draw-heading"><span className="eyebrow">TIRAGE {String(draw).padStart(2, "0")}</span><button className="sheet-entry-action sheet-entry-action--delete" type="button" onClick={() => onDelete(draw)}>Supprimer ce tirage</button></div><div className="sheet-scroll"><table className="sheet-table admin-draw-table"><thead><tr><th>Ligne</th><th>Proposé par</th><th>Écouté par</th><th>Action</th></tr></thead><tbody>{rows.sort((a, b) => a.position - b.position).map((entry) => { const current = field(entry); return <tr key={entry.id}><td>{String(entry.position).padStart(2, "0")}</td><td><MemberSelect value={current.proposer} label="Choisir le proposeur" onChange={(next) => change(entry, "proposer", next)} /></td><td><MemberSelect value={current.listener} label="Choisir la personne qui écoute" onChange={(next) => change(entry, "listener", next)} /></td><td><button type="button" className="sheet-entry-action" disabled={savingId === entry.id} onClick={() => onAssign(entry, current.proposer, current.listener)}>{savingId === entry.id ? "…" : "Enregistrer"}</button></td></tr>; })}</tbody></table></div></section>)}</section>;
}

function Kouize({ answers, member, isAdmin }: { answers: KouizeAnswer[]; member: SignedMember | null; isAdmin: boolean }) {
  const answerMap = new Map(answers.map((answer) => [`${answer.member_username}:${answer.question_key}`, answer.answer]));
  return <section className="quiz-sheet"><div className="quiz-intro kouize-intro"><p className="eyebrow">KOUIZE</p><h2>Un peu plus de goût,<br /><em>un peu moins de hasard.</em></h2><p>{member && !isAdmin ? "Modifie ton Kouize depuis Mon compte." : "Les réponses du club aident à mieux viser les prochaines propositions."}</p></div><div className="quiz-scroll kouize-scroll"><table className="quiz-table kouize-table"><thead><tr><th>Repère</th>{quizMembers.map((name) => <th key={name}>{name}</th>)}</tr></thead><tbody>{quizQuestions.map((question) => <tr key={question.key}><th><span>{question.label}</span><b>{question.question}</b><small>{question.prompt}</small></th>{quizMembers.map((name) => { const username = roster.find((memberEntry) => memberEntry.displayName === name)?.username ?? name.toLowerCase(); return <td key={name}><span className="kouize-answer">{answerMap.get(`${username}:${question.key}`) ?? "—"}</span></td>; })}</tr>)}</tbody></table></div></section>;
}

export function TableurBoard({ albums }: { albums: Album[] }) {
  const configured = isSupabaseConfigured(); const [activeTab, setActiveTab] = useState<Tab>("archive"); const [member, setMember] = useState<SignedMember | null>(null); const [isAdmin, setIsAdmin] = useState(false); const [entries, setEntries] = useState<DrawEntry[]>([]); const [reviews, setReviews] = useState<ReviewRecord[]>([]); const [kouizeAnswers, setKouizeAnswers] = useState<KouizeAnswer[]>([]); const [savingId, setSavingId] = useState<string | null>(null); const [message, setMessage] = useState(""); const [focusedProposal, setFocusedProposal] = useState<string | null>(null); const [focusedReview, setFocusedReview] = useState<string | null>(null);
  const visibleTabs = isAdmin ? [...tabs, adminTab] : tabs; const active = visibleTabs.find((tab) => tab.id === activeTab) ?? tabs[0];
  const loadEntries = useCallback(async () => { if (!configured) return; const columns = member ? "id, draw_number, position, proposed_by, listened_by, proposed_by_name, listened_by_name, album_title, album_artist, cover_path" : "id, draw_number, position, proposed_by_name, listened_by_name, album_title, album_artist, cover_path"; const { data, error } = await getSupabaseBrowserClient().from("club_draw_entries").select(columns).order("draw_number", { ascending: true }).order("position", { ascending: true }); if (!error) setEntries((data ?? []) as DrawEntry[]); }, [configured, member]);
  const loadReviews = useCallback(async () => { if (!configured) return; const { data, error } = await getSupabaseBrowserClient().from("member_album_reviews").select("album_id, review, rating, best_track, worst_track"); if (!error) setReviews((data ?? []) as ReviewRecord[]); }, [configured]);
  const syncAccess = useCallback(async () => { if (!configured) return; const supabase = getSupabaseBrowserClient(); const { data } = await supabase.auth.getUser(); const user = data.user; if (!user) { setMember(null); setIsAdmin(false); setReviews([]); return; } const username = typeof user.app_metadata.username === "string" ? user.app_metadata.username : user.email?.split("@")[0] ?? "membre"; const displayName = roster.find((entry) => entry.username === username)?.displayName ?? username; setMember({ id: user.id, username, displayName }); const { data: profile } = await supabase.from("member_profiles").select("role").eq("id", user.id).maybeSingle(); setIsAdmin(profile?.role === "admin"); await loadReviews(); }, [configured, loadReviews]);
  useEffect(() => { const timer = setTimeout(() => { void loadEntries(); void syncAccess(); if (configured) void getSupabaseBrowserClient().from("member_kouize_answers").select("member_username, question_key, answer").then((result: { data: unknown }) => setKouizeAnswers((result.data ?? []) as KouizeAnswer[])); }, 0); return () => clearTimeout(timer); }, [configured, loadEntries, syncAccess]);
  useEffect(() => { if (!configured) return; const { data } = getSupabaseBrowserClient().auth.onAuthStateChange(() => void syncAccess()); return () => data.subscription.unsubscribe(); }, [configured, syncAccess]);
  const goToProposal = (id: string) => { setFocusedProposal(id); setFocusedReview(null); setActiveTab("selection"); };
  const goToReview = (id: string) => { setFocusedReview(id); setFocusedProposal(null); setActiveTab("selection"); };
  const saveProposal = async ({ entryId, title, artist, file }: ProposalPayload) => { if (!configured || !member) return; setSavingId(entryId); setMessage(""); let cover_path: string | undefined; try { if (file) { if (!new Set(["image/jpeg", "image/png", "image/webp"]).has(file.type) || file.size > 5 * 1024 * 1024) throw new Error("Choisis une image JPG, PNG ou WebP de 5 Mo maximum."); const extension = file.name.split(".").pop()?.toLowerCase() || "jpg"; const path = `${member.id}/${entryId}.${extension}`; const { error } = await getSupabaseBrowserClient().storage.from("album-covers").upload(path, file, { upsert: true, contentType: file.type, cacheControl: "31536000" }); if (error) throw error; cover_path = path; } const update = { album_title: title.trim(), album_artist: artist.trim(), ...(cover_path ? { cover_path } : {}) }; const { error } = await getSupabaseBrowserClient().from("club_draw_entries").update(update).eq("id", entryId); if (error) throw error; setMessage("Album proposé : il apparaît maintenant dans le tirage."); await loadEntries(); } catch (error) { setMessage(error instanceof Error ? error.message : "L’album n’a pas pu être enregistré."); } finally { setSavingId(null); } };
  const saveReview = async ({ entryId, review, rating, bestTrack, worstTrack }: ReviewPayload) => { if (!configured || !member || !review.trim() || !Number.isFinite(rating)) return; setSavingId(entryId); setMessage(""); const { error } = await getSupabaseBrowserClient().from("member_album_reviews").upsert({ album_id: entryId, member_id: member.id, review: review.trim(), rating, best_track: bestTrack.trim() || null, worst_track: worstTrack.trim() || null }, { onConflict: "album_id,member_id" }); setSavingId(null); if (error) setMessage("Ce verdict n’a pas pu être enregistré."); else { setMessage("Verdict enregistré."); await loadReviews(); } };
  const createDraw = async () => { if (!configured || !isAdmin) return; setSavingId("new-draw"); setMessage(""); const { error } = await getSupabaseBrowserClient().rpc("admin_create_club_draw", { p_entry_count: 8 }); setSavingId(null); if (error) setMessage("Le tirage n’a pas pu être créé."); else { setMessage("Nouveau tirage créé."); await loadEntries(); } };
  const assignEntry = async (entry: DrawEntry, proposer: string, listener: string) => { if (!configured || !isAdmin) return; setSavingId(entry.id); setMessage(""); const { error } = await getSupabaseBrowserClient().rpc("admin_update_club_draw_entry", { p_entry_id: entry.id, p_proposer_username: proposer, p_listener_username: listener }); setSavingId(null); if (error) setMessage("Cette ligne n’a pas pu être enregistrée."); else { setMessage("Ligne de tirage enregistrée."); await loadEntries(); } };
  const deleteDraw = async (draw: number) => { if (!configured || !isAdmin || !confirm(`Supprimer le tirage ${draw} ?`)) return; setSavingId(`delete-${draw}`); const { error } = await getSupabaseBrowserClient().rpc("admin_delete_club_draw", { p_draw_number: draw }); setSavingId(null); if (error) setMessage("Le tirage n’a pas pu être supprimé."); else { setMessage("Tirage supprimé."); await loadEntries(); } };
  return <section className="tableur-board" aria-label="Tableur du DOL ZIKLUB"><div className="sheet-tabs" role="tablist">{visibleTabs.map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={activeTab === tab.id} className={activeTab === tab.id ? "active" : ""} onClick={() => setActiveTab(tab.id)}>{tab.label}</button>)}</div><div className="sheet-meta"><span className="eyebrow">{active.label}</span><span>{active.hint}</span></div>{message && <p className="selection-message" role="status">{message}</p>}<div role="tabpanel">{activeTab === "archive" && <div className="sheet-archive"><HistoricalDraws albums={albums} /><LiveDraws entries={entries} member={member} onOpenProposal={goToProposal} onOpenReview={goToReview} /></div>}{activeTab === "selection" && <SelectionWorkspace entries={entries} member={member} reviews={reviews} focusedProposal={focusedProposal} focusedReview={focusedReview} savingId={savingId} onProposal={(payload) => void saveProposal(payload)} onReview={(payload) => void saveReview(payload)} />}{activeTab === "kouize" && <Kouize answers={kouizeAnswers} member={member} isAdmin={isAdmin} />}{activeTab === "admin" && isAdmin && <AdminDraws entries={entries} savingId={savingId} message="" onCreate={() => void createDraw()} onDelete={(draw) => void deleteDraw(draw)} onAssign={(entry, proposer, listener) => void assignEntry(entry, proposer, listener)} />}</div></section>;
}
